# Generated by Django 3.2.1 on 2021-05-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mortgage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_price', models.IntegerField()),
                ('initial_payment', models.IntegerField()),
                ('period', models.IntegerField()),
                ('interest_rate', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('monthly_payment', models.IntegerField()),
                ('comment', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
