# Generated by Django 3.2.1 on 2021-05-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210516_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortgage',
            name='period',
            field=models.FloatField(),
        ),
    ]
