# Generated by Django 3.2.1 on 2021-05-19 19:31

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210517_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mortgage',
            name='comment',
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='full_price',
            field=models.IntegerField(validators=[app.models.positive_number]),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='initial_payment',
            field=models.IntegerField(validators=[app.models.positive_number]),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='interest_rate',
            field=models.FloatField(validators=[app.models.positive_number, app.models.max_rate]),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='period',
            field=models.IntegerField(validators=[app.models.positive_number]),
        ),
    ]
